version: '3.9'

services:
  pgSQL-db:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_DOCKER=${POSTGRES_HOST}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
    ports:
      - "5430:${POSTGRES_PORT}"
    restart: on-failure
    volumes:
      - database-data:/var/lib/postgresql@14/auth/data/
    networks:
          - database

  redis-db:
    image: 'redis:latest'
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_URL=${REDIS_URL}    
    ports:
      - "6379:${REDIS_PORT}"
    restart: on-failure
    volumes:
      - database-data:/var/lib/postgresql@14/auth/data/
    networks:
          - database    

  app:
    build:
        dockerfile: DockerFile
   
    ports:
      - 8080:8080 
    
    tty: true
    depends_on:
      - pgSQL-db 
      - redis-db
    restart: on-failure  
    networks:
      - database

networks:
  database:
    driver: bridge


volumes:
  data:
  database-data: