FROM golang:1.19-alpine AS builder

WORKDIR /build

ADD go.mod .

COPY . .

RUN apk update && apk add git
RUN go build -o ./cache ./cmd/main.go

FROM alpine

WORKDIR /build

COPY --from=builder /build/cache /build/cache
COPY --from=builder /build/.env .


CMD ["./cache"]
