env: "test"

pgSQL: 
  port: "5432"
  host: "0.0.0.0"
  user: "pgSQL"
  password: "admin"
  DBName: "article"
  SSLMode: "disable"  

redis: 
  port: "6379"
  host: "0.0.0.0"
  password: ""  
  DB: 0
  timeout: 1m

httpServer:
  port: "8080"
  host: "0.0.0.0"
  readTimeout: 10s
  writeTimeout: 10s

