name: Deploy App

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: https://api.render.com/deploy/srv-ckslrm6nfb1c73bm4sc0?key=hqixM_U4N4I
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2       
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.7
      - name: Build app
        run: |
          go mod download      
      - name: Run Tests
        run: go test ./... 
      - name: Build app   
        run: 
          go build cmd/main.go 
      - name: Deploy to server
        run: |
          RESPONSE=$(curl -s "$DEPLOY_URL")
          echo "HTTP Response: $RESPONSE"     